language: php
dist: precise
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - cd ./tests/
  - ../vendor/bin/phpunit

after_script:
  - ../vendor/bin/ocular code-coverage:upload --format=php-clover ../build/logs/clover.xml

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: 5.6
    - php: hhvm
